# Generated by Django 2.2.3 on 2019-07-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryBill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('itemType', models.CharField(max_length=30)),
                ('otherCharges', models.CharField(max_length=30)),
            ],
        ),
    ]
